README: Exclude python version range that breaks building
Attempting to build with 3.10 to 3.10.1 results in the following error:

`ImportError: cannot import name 'Mapping' from 'collections'`

See https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections